---
title: "remote-sensing-ms-intro"
author: "Clay Morrow"
date: "12/7/2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Appropriate hypothesis tests of time trends in spatial data must account for
spatial and temporal autocorrelation. The new method developed by 
Ives et al (unpublished) does so in an elegegant and efficient manor that 
traditional methods do not. However, as described, these methods can only be 
used to predict the effects of temporally constant factors. Here, I propose to
extend the methods of Ives et al by allowing for the use of spatio-temporally 
autocorrelated predictors. I will test the extended methods by applying them 
to data simulated with the expected underlying structure. I will then apply
the method to a real world data set to test the hypothesis that temperature is
driving changes in phenology in certain land classes. 

A spatio-temporally autocorrelated variable of interest follows the form: 

$$ x_i(t) = \alpha_{i} + \beta_{i}x_{i}(t - 1) + \gamma_{i}t + \varepsilon_{i}(t)  \tag{1}$$

where:

* $x_i(t)$ is the value of the variable at pixel $i$ at time $t$
* $\alpha_i$ is the model intercept at pixel $i$
* $\beta_i$ is the effect of the pixel's value at the previous time point 
$x_i(t-1)$ on the current value of $x_i$
* $\gamma_i$ is the effect of time $t$ on $x_i$
* and $\varepsilon_{i}(t) \sim N(0, \Sigma_x)$ is the random correlated error 
term: 
  - $\Sigma_x = (1 - \eta_{x}) C_{x} + \eta_{x} I$ is the correlation structure 
  of $x_i$ where 
  - $C_x$ is the spatial correlation matrix of $x_i$, 
  - $\eta_x$ is a nugget that absorbs additional random variation among the 
  $x_i$s, and 
  - $I$ is an identity matrix

And a predictor variable of interest follows the very similar form but with 
different parameter names for the sake of clarity:

$$ z_i(t) = \nu_{i} + \lambda_{i}z_{i}(t-1) + \kappa_{i}t + \varepsilon_{i}(t) \tag{2}$$
<!-- And a response generated by a base-line correlation structure **and** the  -->
<!-- effects of a predictor with similar variance structure follows: -->

<!-- $$y_i(t) = x_i(t) + \theta z_i(t) $$ -->

<!-- where $\theta$ is the effect of $z$ on the response $y$.  -->

## GLS

The GLS model using site-specific and non-temporally variable predictors 
(i.e. land cover classification) is performed by regressing the temporally
collapsed response against them:

$$\hat{\gamma} = bX + \varepsilon \tag{3}$$

where 

* $\hat{\gamma}$ is an $n$ length vector of temporally collapsed pixel-level 
time trend estimates from formula (1) obtained via CLS, 
* $X$ is an $n \times p$ design matrix of fixed site-level predictors (possibly 
including an intercept),
* $b$ is a $p$ length vector of effects for each predictor, and
* $\varepsilon \sim N(0, \Sigma)$ is the random error term whose covariance 
matrix $\Sigma$ is equivalent to $\Sigma_x$ which holds the spatial correlation 
and nugget for $x_i$. 

in this model, the best-linear unbiased estimators $\hat{b}$ 
are obtained via the formula

$$\hat{b} = (X'\Sigma^{-1}X)^{-1} (X'\Sigma^{-1}\hat{\gamma}) \tag{4}$$

and the expected variance of $\hat{b}$ is 

$$ \text{var}(\hat{b}) = (X'\Sigma^{-1}X)^{-1} \tag{5}$$

However, if the predictor is not constant over time, but is instead spatially 
and temporally variable (and autocorrelated), it is necessary to modify the 
process:

$$\hat{\gamma} = b\hat{X} + \varepsilon  \tag{6}$$
where $X$ has been replaced with $\hat{X}$ which 
represents an $n \times p$ design matrix of temporally collapsed predictors 
(i.e. CLS estimate estimate of $\kappa$ from formula (2) ). Because the
assumptions of GLS only involve the correlation pattern of the response, it
is not necessary to account for the spatial component of $\hat{X}$ directly. 
The regression should be able to detect when the variance structure of $\hat{X}$
differs from the provided structure of $\hat{\gamma}$. If additional variance is 
explained by $\hat{X}$, it should produce a significant $\beta$.

To test this, I will apply the above method to simulated responses generated 
with a base-line spatio-temporal autocorrelation and the effect of a 
spatio-temporally autocorrelated predictor variable: 
$y_i(t) = x_i(t) + \theta z_i(t)$.

## Variance Partitioning

The covariance structure of $y_i(t) = x_i(t) + \theta z_i(t)$ is
$\Sigma_y = \Sigma_x + \Sigma_z$. So, we should theoretically be able to recover 
the covariance structure of $x_i(t)$ by estimating the differences between $y$ and 
$z$ (i.e $\hat\Sigma_y - \hat\Sigma_z$). This would give us the variation in our
response $y$ that is not explained by variation in out spatio-temporally 
structured predictor $z$. If the spatial correlations for $x$ and $z$ are 
equivalent (i.e. equal range of spatial autocorrelation; $C_x = C_z = C$), then 
the equation can be reduced to

$$\Sigma_x = \Sigma_y - \Sigma_z = (\eta_x)C - (\eta_x)I \tag{7}$$ 

where the nugget for $y$ is $\eta_y = \eta_z - \eta_x$.

To test if $z$ is driving changes in $y$, we would ask if variation in $z$ 
(including spatial variation) explains significant variation in $y$. In other 
words, we would test against the null hypothesis that $\Sigma_z$ is a very 
small (0) proportion of $\Sigma_y$ (i.e. $H_0: \frac{\Sigma_z}{\Sigma_x} = 0$) 

## Questions

With this method for predicting spatio-temporally correlated responses from 
spatio-temporally correlated predictors, we can appropriate test hypotheses 
about the effects of climate on ecological responses. For example, we can test 
the hypothesis that increasing temperature is associated with earlier onset of
photosynthesis in particular land classes. 
